import type { ExportColumn, ExportDefinition, OperationalExportType } from './types';

const column = (key: string, label: string, type: ExportColumn['type']): ExportColumn => ({
  key,
  label,
  type,
});

const masterFilters = ['search', 'isActive'] as const;
const productFilters = [...masterFilters, 'categoryId', 'productType', 'unit'] as const;

const definitions: Readonly<Record<OperationalExportType, ExportDefinition>> = {
  PRODUCTS: {
    type: 'PRODUCTS',
    fileSlug: 'produtos',
    sheetName: 'Produtos',
    allowedFilters: productFilters,
    columns: [
      column('product_id', 'ID do produto', 'UUID'),
      column('sku', 'SKU', 'TEXT'),
      column('ean', 'EAN', 'TEXT'),
      column('name', 'Produto', 'TEXT'),
      column('category_id', 'ID da categoria', 'UUID'),
      column('category', 'Categoria', 'TEXT'),
      column('product_type', 'Tipo', 'TEXT'),
      column('unit', 'Unidade', 'TEXT'),
      column('minimum_quantity', 'Quantidade mínima', 'DECIMAL'),
      column('active', 'Ativo', 'BOOLEAN'),
      column('created_at', 'Criado em', 'DATETIME'),
      column('updated_at', 'Atualizado em', 'DATETIME'),
    ],
  },
  CATEGORIES: {
    type: 'CATEGORIES',
    fileSlug: 'categorias',
    sheetName: 'Categorias',
    allowedFilters: masterFilters,
    columns: [
      column('category_id', 'ID da categoria', 'UUID'),
      column('name', 'Categoria', 'TEXT'),
      column('description', 'Descrição', 'TEXT'),
      column('active', 'Ativa', 'BOOLEAN'),
      column('created_at', 'Criada em', 'DATETIME'),
      column('updated_at', 'Atualizada em', 'DATETIME'),
    ],
  },
  LOCATIONS: {
    type: 'LOCATIONS',
    fileSlug: 'locais',
    sheetName: 'Locais',
    allowedFilters: [...masterFilters, 'locationType'],
    columns: [
      column('location_id', 'ID do local', 'UUID'),
      column('name', 'Local', 'TEXT'),
      column('description', 'Descrição', 'TEXT'),
      column('location_type', 'Tipo do local', 'TEXT'),
      column('active', 'Ativo', 'BOOLEAN'),
      column('created_at', 'Criado em', 'DATETIME'),
      column('updated_at', 'Atualizado em', 'DATETIME'),
    ],
  },
  SUPPLIERS: {
    type: 'SUPPLIERS',
    fileSlug: 'fornecedores',
    sheetName: 'Fornecedores',
    allowedFilters: masterFilters,
    columns: [
      column('supplier_id', 'ID do fornecedor', 'UUID'),
      column('document', 'Documento', 'TEXT'),
      column('legal_name', 'Razão social', 'TEXT'),
      column('trade_name', 'Nome fantasia', 'TEXT'),
      column('active', 'Ativo', 'BOOLEAN'),
      column('created_at', 'Criado em', 'DATETIME'),
      column('updated_at', 'Atualizado em', 'DATETIME'),
    ],
  },
  STOCK_CURRENT: {
    type: 'STOCK_CURRENT',
    fileSlug: 'estoque-atual',
    sheetName: 'Estoque atual',
    allowedFilters: productFilters,
    columns: [
      column('product_id', 'ID do produto', 'UUID'),
      column('sku', 'SKU', 'TEXT'),
      column('ean', 'EAN', 'TEXT'),
      column('name', 'Produto', 'TEXT'),
      column('category_id', 'ID da categoria', 'UUID'),
      column('category', 'Categoria', 'TEXT'),
      column('product_type', 'Tipo', 'TEXT'),
      column('unit', 'Unidade', 'TEXT'),
      column('current_quantity', 'Quantidade atual', 'DECIMAL'),
      column('minimum_quantity', 'Quantidade mínima', 'DECIMAL'),
      column('situation', 'Situação', 'TEXT'),
      column('active', 'Ativo', 'BOOLEAN'),
      column('stock_updated_at', 'Saldo atualizado em', 'DATETIME'),
      column('product_updated_at', 'Produto atualizado em', 'DATETIME'),
    ],
  },
  STOCK_MOVEMENTS: {
    type: 'STOCK_MOVEMENTS',
    fileSlug: 'movimentacoes-estoque',
    sheetName: 'Movimentações',
    allowedFilters: ['search', 'productId', 'movementType', 'createdFrom', 'createdTo'],
    columns: [
      column('movement_id', 'ID da movimentação', 'UUID'),
      column('product_id', 'ID do produto', 'UUID'),
      column('sku', 'SKU', 'TEXT'),
      column('product_name', 'Produto', 'TEXT'),
      column('movement_type', 'Tipo', 'TEXT'),
      column('quantity', 'Quantidade', 'DECIMAL'),
      column('unit', 'Unidade', 'TEXT'),
      column('source_location_id', 'ID da origem', 'UUID'),
      column('source_location', 'Origem', 'TEXT'),
      column('destination_location_id', 'ID do destino', 'UUID'),
      column('destination_location', 'Destino', 'TEXT'),
      column('invoice_id', 'ID da NF', 'UUID'),
      column('invoice_number', 'Número da NF', 'TEXT'),
      column('import_batch_id', 'ID do lote', 'UUID'),
      column('import_source', 'Origem da importação', 'TEXT'),
      column('reference_id', 'ID de referência', 'UUID'),
      column('reason', 'Motivo', 'TEXT'),
      column('responsible_user_id', 'ID do responsável', 'UUID'),
      column('responsible', 'Responsável', 'TEXT'),
      column('created_at', 'Data', 'DATETIME'),
    ],
  },
  LOSSES: {
    type: 'LOSSES',
    fileSlug: 'perdas',
    sheetName: 'Perdas',
    allowedFilters: ['search', 'productId', 'categoryId', 'locationId', 'createdFrom', 'createdTo'],
    columns: [
      column('loss_id', 'ID da perda', 'UUID'),
      column('movement_id', 'ID da movimentação', 'UUID'),
      column('product_id', 'ID do produto', 'UUID'),
      column('sku', 'SKU', 'TEXT'),
      column('product_name', 'Produto', 'TEXT'),
      column('category_id', 'ID da categoria', 'UUID'),
      column('category', 'Categoria', 'TEXT'),
      column('quantity', 'Quantidade', 'DECIMAL'),
      column('unit', 'Unidade', 'TEXT'),
      column('location_id', 'ID do local', 'UUID'),
      column('location', 'Local', 'TEXT'),
      column('reason', 'Motivo', 'TEXT'),
      column('notes', 'Observação', 'TEXT'),
      column('responsible_user_id', 'ID do responsável', 'UUID'),
      column('responsible', 'Responsável', 'TEXT'),
      column('created_at', 'Data', 'DATETIME'),
    ],
  },
  INVOICES: {
    type: 'INVOICES',
    fileSlug: 'notas-fiscais',
    sheetName: 'Notas fiscais',
    allowedFilters: [
      'search',
      'supplierId',
      'productId',
      'categoryId',
      'invoiceStatus',
      'createdFrom',
      'createdTo',
    ],
    columns: [
      column('invoice_id', 'ID da NF', 'UUID'),
      column('access_key', 'Chave de acesso', 'TEXT'),
      column('invoice_number', 'Número da NF', 'TEXT'),
      column('series', 'Série', 'TEXT'),
      column('invoice_status', 'Status', 'TEXT'),
      column('issued_at', 'Emitida em', 'DATETIME'),
      column('imported_at', 'Importada em', 'DATETIME'),
      column('supplier_id', 'ID do fornecedor', 'UUID'),
      column('supplier_document', 'Documento do fornecedor', 'TEXT'),
      column('supplier_legal_name', 'Razão social', 'TEXT'),
      column('supplier_trade_name', 'Nome fantasia', 'TEXT'),
      column('invoice_item_id', 'ID do item', 'UUID'),
      column('line_number', 'Linha', 'TEXT'),
      column('product_id', 'ID do produto', 'UUID'),
      column('sku', 'SKU', 'TEXT'),
      column('product_name', 'Produto', 'TEXT'),
      column('category_id', 'ID da categoria', 'UUID'),
      column('category', 'Categoria', 'TEXT'),
      column('supplier_product_code', 'Código no fornecedor', 'TEXT'),
      column('item_description', 'Descrição do item', 'TEXT'),
      column('quantity', 'Quantidade', 'DECIMAL'),
      column('unit', 'Unidade', 'TEXT'),
      column('unit_price', 'Valor unitário', 'DECIMAL'),
      column('total_amount', 'Valor total', 'DECIMAL'),
      column('responsible_user_id', 'ID do responsável', 'UUID'),
      column('responsible', 'Responsável', 'TEXT'),
      column('created_at', 'Criada em', 'DATETIME'),
    ],
  },
  PRODUCTS_WITH_CURRENT_STOCK: {
    type: 'PRODUCTS_WITH_CURRENT_STOCK',
    fileSlug: 'produtos-com-estoque-atual',
    sheetName: 'Produtos e estoque',
    allowedFilters: productFilters,
    columns: [
      column('product_id', 'ID do produto', 'UUID'),
      column('sku', 'SKU', 'TEXT'),
      column('ean', 'EAN', 'TEXT'),
      column('name', 'Produto', 'TEXT'),
      column('category_id', 'ID da categoria', 'UUID'),
      column('category', 'Categoria', 'TEXT'),
      column('product_type', 'Tipo', 'TEXT'),
      column('unit', 'Unidade', 'TEXT'),
      column('current_quantity', 'Quantidade atual', 'DECIMAL'),
      column('minimum_quantity', 'Quantidade mínima', 'DECIMAL'),
      column('situation', 'Situação', 'TEXT'),
      column('active', 'Ativo', 'BOOLEAN'),
      column('stock_updated_at', 'Saldo atualizado em', 'DATETIME'),
      column('product_updated_at', 'Produto atualizado em', 'DATETIME'),
    ],
  },
};

export function getExportDefinition(type: OperationalExportType): ExportDefinition {
  return definitions[type];
}

export const OPERATIONAL_EXPORT_DEFINITIONS = definitions;
